### ISSUE TITLE
Out of the box tracing of web server endpoints

### ISSUE THREAD

**Issue by smiles3983** [Dynatrace/OneAgent-SDK-for-Python#10]
I would like to be able to initialize the SDK and have it automatically detect calls made to my web service framework's endpoints.  Currently, I have to add the tracing calls to any function I want to trace.  this makes sense if I want to trace functions deep inside my code, but for endpoint requests, I think it should just grab them automatically.  This is how it works for IIS and other web services even without an SDK needed.

**Comment by Oberon00** [comment]
Hi! We do not plan to add any automatic instrumentation support to the SDK. However, most webframeworks support some middleware concept that allows you to plug in the SDK yourself with a little work. For example, if you are using Flask or some other WSGI-based framework, this blogpost may help you: https://www.dynatrace.com/news/blog/from-monitoring-to-software-intelligence-for-flask-applications/ (Sample code: https://github.com/Dynatrace/snippets/tree/master/technologies/python/flask)

**Comment by Oberon00** [comment]
There is now also https://github.com/dynatrace-oss/OneAgent-SDK-Python-AutoInstrumentation
