### ISSUE TITLE
Path creation unsuccessful (incoming tag type: String) / Path creation unsuccessful (incoming tag type: Nothing).

### ISSUE THREAD

**Issue by ryankimavodaq** [Dynatrace/OneAgent-SDK-for-Python#13]
I am unable to resolve this issue. Does anyone know what is causing this error. The following function  `onesdk_tracer_start'(IncomingWebRequest)` was not invoked yet it is showing up as an error. Thank you. 
```
2019-11-01 09:11:22.514 UTC [eb60a83e] info    [native] NOTE: No path available: in 'onesdk_tracer_start'(IncomingWebRequest): Path creation unsuccessful (incoming tag type: String).
2019-11-01 09:11:22.526 UTC [eb60a83e] info    [native] NOTE: No path available: in 'onesdk_tracer_start'(OutgoingWebRequest): Path creation unsuccessful (incoming tag type: Nothing).
```

**Comment by Oberon00** [comment]
Hi,
first of all, this is not an error message, it's just informational and can occur for various reasons, so you should just ignore it, unless you have an actual problem (if that's the case, please state it).

Second, the message comes from the OneAgent and was written with the the OneAgent SDK for C/C++ in mind. The OneAgent SDK for Python uses the C/C++ SDK to communicate with the OneAgent and calls the C function `onesdk_tracer_start` when you call `start` on a tracer or enter a `with tracer:` block. In that case, your code probably actually looks like:

```python
with oneagent.get_sdk().trace_incoming_web_request(...):
 # ...
```

or

```python
tracer =  oneagent.get_sdk().trace_incoming_web_request(...)
tracer.start()
```

**Comment by Oberon00** [comment]
Closing this issue, as it is stale.
