### ISSUE TITLE
PyPI Version Issue

### ISSUE THREAD

**Issue by azizabah** [Dynatrace/OneAgent-SDK-for-Python#15]
It looks like the 1.3.0 version had issues with its semantic versioning when pushed to PyPi https://pypi.org/project/oneagent-sdk/1.3.0.20191113.161138/#history

**Comment by z1c0** [comment]
Unfortunately, this version numbering scheme is intentional (ugly as it is), due to a changed build and deployment process on our side.
This might be addressed in an upcoming version though.

**Comment by Oberon00** [comment]
Did that change cause any issues for you? Or did you just find it strange?

**Comment by azizabah** [comment]
@Oberon00 - No not really. I just found it strange and inconsistent with previous versioning. 
@z1c0  - If anyone outside of Dynatrace gets a vote, going back to your old semantic versioning would be appreciated.
