### ISSUE TITLE
More transparent active tracer / add_custom_request_attribute

### ISSUE THREAD

**Issue by romanskas** [Dynatrace/OneAgent-SDK-for-Python#16]
Hi, I would like to ask some more transparency for tracer handling. The add_custom_request_attribute function requires an active tracer to succeed. Unfortunately, until now there is no way to check if it succeeded or failed. Applications need to keep track on tracers explicitly, which is error-prone. As a quick-fix it would suffice if add_custom_request_attribute returns a Boolean value or an error code. Alternative and more general solution is to offer access to the active tracer object.

**Comment by Oberon00** [comment]
Why would you need to know if `add_custom_request_attribute` suceeded? What would you do in case of error?

**Comment by romanskas** [comment]
In my particular use-case, I would create a custom service tracer and retry the attribute creation. Alternative uses is to raise an exception or write a warning into the log.

**Comment by Oberon00** [comment]
What about just always creating a custom service tracer?

**Comment by romanskas** [comment]
It will surely work, but I would prefer to re-use an existing tracer if it is available.

**Comment by z1c0** [comment]
FYI @dtPaTh @SonjaChevre

**Comment by Oberon00** [comment]
Closing as stale. If this is still an issue please comment.
