### ISSUE TITLE
Support for Python SDK for Alpine

### ISSUE THREAD

**Issue by amarlot** [Dynatrace/OneAgent-SDK-for-Python#17]
Hello Dynatrace team,

Currently the SDK is not supported with Alpine. Alpine is used more and more for apps inside container.

It would be very nice to have it as currently we can't monitor some of our app because we use alpine as OS.

Any plan to support it ? 

I have seen here. It is in "future" status : https://www.dynatrace.com/support/help/setup-and-configuration/dynatrace-oneagent/oneagent-technology-support/oneagent-platform-and-capability-support-matrix/

Thanks,
Alexandre

**Comment by z1c0** [comment]
Hi Alexandre,

while support for Alpine Linux is a roadmap item, there is currently no definitive ETA for it. Sorry.

-Wolfgang

FYI: @dtPaTh @SonjaChevre
