### ISSUE TITLE
Add Python code-level visibility via SDK

### ISSUE THREAD

**Issue by tomdesair** [Dynatrace/OneAgent-SDK-for-Python#18]
Hi,

Currently we see the following code-leve details after instrumenting our API endpoints with the Python SDK: https://1drv.ms/u/s!AtRjMrJnRHluhaxt7nQJ68lInccqNg

We were wondering if there is a way (using the SDK) to add more information on the actual Python functions that are invoked when processing this API call and how long each Python function takes.

We don't want to create additional Service objects (with the Custom tracer functionality). We want to add code-level details within the current Service object.

Is this already possible? Or is this a feature on the roadmap?

**Comment by z1c0** [comment]
Hi Tom,

the functionality you are looking for can only be accomplished using [custom services](https://github.com/Dynatrace/OneAgent-SDK-for-Python#custom-services).

(FYI @dtPaTh @SonjaChevre)

**Comment by tomdesair** [comment]
Hi @z1c0,

We already tried to use the custom services approach. However, we do not want to create a (new) custom service for every Python module.

We're looking for a way to show code-level details inside a custom service under the "Code level" tab (see https://1drv.ms/u/s!AtRjMrJnRHluhaxt7nQJ68lInccqNg).

Is this feature already on a road map somewhere? Or can I submit a feature request for this somewhere?

Thanks in advance!

**Comment by z1c0** [comment]
Hi Tom, 

I'm sorry, there's no such feature now and neither on the roadmap at the moment.
There is https://answers.dynatrace.com/ for new feature requests.

-Wolfgang

**Comment by tomdesair** [comment]
FYI, I created the feature request here: https://answers.dynatrace.com/spaces/483/dynatrace-product-ideas/idea/240105/rfe-trace-code-level-functions-in-custom-service-u.html
