### ISSUE TITLE
Multiple tracers per thread: allowed?

### ISSUE THREAD

**Issue by yunduz** [Dynatrace/OneAgent-SDK-for-Python#20]
Hello! I've read in the documentation that tracer should be started and ended by the same thread. However, I am wondering if one thread can start and end multiple tracers of the same type? I am getting errors in my service and I am questioning if that could be the reason why.

I am using [FastAPI](https://fastapi.tiangolo.com/) web framework where one thread handles multiple incoming web requests concurrently (it switches between request whenever one of the requests needs to wait on something). Whenever new requests comes in, incoming web request tracer is started, and on completion tracer is ended. Thus, it could be the case that the same thread starts multiple tracers and closes them in an undefined order. For example, thread could execute tracer-related statements in this order:

```
tracer1.start
tracer2.start
tracer1.end
tracer3.start
tracer2.end
tracer3.end
```

The errors I am seeing in my application logs are the following:

```
2020-11-02 19:16:38,283  [ERROR] MainThread - NOTE: Marking sub-path as broken. Reason: unexpected error while trying to exit (end) a node - see following messages.
2020-11-02 19:16:38,283  [ERROR] MainThread - Removing path. Reason: broken.
2020-11-02 19:16:38,283  [ERROR] MainThread - WARNING: Wrong node state: in 'onesdk_tracer_end'(IncomingWebRequest): cannot exit a node that isn't top-of-stack.
```

And the matching agent logs:

```
2020-11-02 19:16:38.283 UTC warning [native] PATH  EXEC  tagId(737807) sensorId(102) HPurePath(0x0000421b00000001) inconsistency (MethodExitMissing): Path ended, but current method node misses exit call NODE: SDK Method depth(1) serialNo(188878636) unused(FALSE) aggr[excl(FALSE) info(FALSE) root(FALSE) fin(FALSE)] method[0x48ad19521e8c01af,OneAgent SDK.Incoming web request, cat=WebRequest, art(TRUE)] contentChged(TRUE) Attachments(WebRequestAttachment ) 
2020-11-02 19:16:38.283 UTC info    [native] WARNING: Wrong node state: in 'onesdk_tracer_end'(IncomingWebRequest): cannot exit a node that isn't top-of-stack.
```

It would be helpful to know whether it is a right way or not to use tracers like that (one thread with multiple tracers).

**Comment by Oberon00** [comment]
Hello @yunduz! The problem here is not the multiple tracers per se but rather that they are not ended in reverse order of starting. The error message `cannot exit a node that isn't top-of-stack` refers to that: When you start a tracer, the SDK puts it on a per-thread stack of active tracers (any tracer previously on top of that stack automatically becomes the parent of the new tracer). When ending a tracer, each child must be ended before its parent. Thus when ending a tracer, the SDK checks that it is at the top of the current thread's stack, i.e. it is started on this thread and has no un-ended children.

As a consequence of this, the SDK is not really suitable for async-style programming where the same thread executes more than one request in parallel.

**Comment by yunduz** [comment]
Hi @Oberon00 ! Thank you very much for your explanation! It makes sense now.

**Comment by tc8** [comment]
Hi @Oberon00, just to confirm, that limitation is in the native SDK and not just the Python SDK right?

Is there a way we can inform Dynatrace about web requests without using a Tracer object? For example, if we measure the latency of requests ourselves, is there a way to tell Dynatrace that a request was just processed and it took X time?

**Comment by z1c0** [comment]
Hi @tc8,

what you are describing could maybe be solved via metrics.
Dynatrace recently added a [metric ingestion protocol](https://www.dynatrace.com/support/help/how-to-use-dynatrace/metrics/metric-ingestion/metric-ingestion-protocol/) that you could consider.

Additionally, we are working on [OpenTelemetry](https://opentelemetry.io/) metric exporters that will allow metric reporting on an API/SDK level. These are not public yet, but you might want to watch https://github.com/dynatrace-oss for that.

**Comment by yunduz** [comment]
Hi @z1c0 ,

Just to make sure I understand correctly:
Does it mean there are no plans to make the SDK support ASGI? Instead, there will be OpenTelemetry Dynatrace Exporter for Python which we can use with OpenTelemetry Instrumentation which already supports [ASGI](https://opentelemetry-python.readthedocs.io/en/stable/instrumentation/asgi/asgi.html) and [FastAPI](https://opentelemetry-python.readthedocs.io/en/stable/instrumentation/fastapi/fastapi.html). Is this right? 
Also, what is the timeframe for the Dynatrace exporter? Is it months/weeks/undefined?

**Comment by z1c0** [comment]
Hi @yunduz,

correct, there are currently no plans to make the SDK support ASGI.

Regarding OpenTelemetry, I'm afraid this was a misunderstanding. The Dynatrace exporter which is currently in development (@arminru do we have an ETA already?) only applies to sending **metric data** at the moment. Instrumentation for tracing/spans is a whole other topic.
The suggestion regarding metrics was only in regard to your question about an alternative approach.
> For example, if we measure the latency of requests ourselves, is there a way to tell Dynatrace that a request was just processed and it took X time?
