### ISSUE TITLE
Trace Context - Missing func oneAgentSDK.getTraceContextInfo in order to fetch Span_Id and Trace_id 

### ISSUE THREAD

**Issue by cscotti** [Dynatrace/OneAgent-SDK-for-Python#24]
Contrary to Java SDK, Python OneAgent SDK do not provides access to TraceContextInfo which holds information about the Trace-Id and Span-Id of the current PurePath node.

Could you add functions which do the same call as Java SDK (missing funcs: TraceContextInfo, getTraceId, getSpanId)? 

NOTE: The java code documentation is accessible thought this url tag `https://github.com/Dynatrace/OneAgent-SDK/blob/master/README.md#trace-context`.

**Comment by Oberon00** [comment]
Hi, this has now been implemented with #25, which is released as v.1.5.0. See https://dynatrace.github.io/OneAgent-SDK-for-Python/docs/sdkref.html#oneagent.sdk.SDK.tracecontext_get_current

**Comment by Oberon00** [comment]
(Aside: The repository you linked is not the actual Java implementation, but the reference/specification repository which contains a mock Java interface as better pseudo code; the Java SDK does not have any W3C trace context APIs yet)

**Comment by cscotti** [comment]
Hi,
Thanks a lot for your submit ;-)
I which you an happy new year
