### ISSUE TITLE
Given that Alpine image is not supported what images of python are recommended to use?

### ISSUE THREAD

**Issue by ayanit1** [Dynatrace/OneAgent-SDK-for-Python#37]
We have attempted to use `python:3.11.9-slim-bullseye` but come across loads of vulnerabilities when it comes to container scanning. We wanted to ask what package is recommended to be used? or what package are people generally using?

**Comment by Oberon00** [comment]
A recommendation for a non-Alpine Python container is not really specific to the OneAgent SDK and I also am not knowledgeable enough myself to give a recommendation from the top of my head, sorry.
