### ISSUE TITLE
Set start_time and end_time manually on Trace_incoming_web_request, trace_outcoming_web_request,...

### ISSUE THREAD

**Issue by cscotsepho** [Dynatrace/OneAgent-SDK-for-Python#38]
Hi, we try to reconstruct services base on our logs for saas application. It works fine with the SDK. The problem is that the one agent will put itself the start and end timestamps. It could be wrong if the logs are parse and process late especially if they are some spicks of logs (5 or 20 minutes delay, even more).

As in open telemetry, could you provide a possibility to let us define manually the correct start_time and end_time (timestamps) on :
- trace_incoming_web_request, 
- trace_outcoming_web_request, 
- trace_custom_service.

We find a by pass with open telemetry. But with this solution, we lost the service flow visualisation.

If possible, we would like to not implement hybride ingestion solutions (One Agent + Open Telemetry) in order to have an expected distributed traces with all the features that dynatrace could provide (based on One Agent ingestion).

**Comment by Oberon00** [comment]
This kind of scenario is out of scope for the OneAgent SDK. It would also not be really easy to implement as OneAgent has rather involved time handling and accepting an external timestamp would not be straightforward.
